### ISSUE TITLE
Change android.permission.CAMERA to android.permission.FLASHLIGHT

### ISSUE THREAD

**Issue by vanitasvitae** [SecUSo/privacy-friendly-torchlight#2]
Hi
As far as I know, the permission to use the camera is not needed in order to turn the flashlight on and off. You should be able to remove the privacy-unfriendly permission for camera usage.

**Comment by p-rack** [comment]
Hi,
thank you for your suggestion. I tested it myself and searched the web for the last days and the result ist the following: you cannot control the LED without the camera permission. 
In fact, the CAMERA permission implicitly allows the use of the LED, without defining the FLASHLIGHT permission. But the FLASHLIGHT permission alone is not enough, because you need the camera in order to control the LED programmatically. If you figured out a possibility feel free to contact us again!
